CC=gcc
FLAGS=-Wall -ggdb


all:myls myshell
	
myls:myls.c
	$(CC) $(FLAGS) -o myls myls.c apue.h

myshell:myshell.c
	$(CC) $(FLAGS) -o myshell myshell.c apue.h
	


clean:
	@rm -f *.o myls myshell 










